apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: speedtest-exporter
spec:
  selector:
    matchLabels:
      app: speedtest-exporter
  template:
    metadata:
      labels:
        app: speedtest-exporter
    spec:
      containers:
        - name: speedtest-exporter
          image: allamedo/speedtest-exporter #localhost:31000/ip-change-alert:k8s
          imagePullPolicy: Always
          ports:
          - containerPort: 8080